FROM php:8.3-cli
WORKDIR /app
RUN docker-php-ext-install pdo pdo_mysql
COPY . .
EXPOSE 8000
CMD ["php", "-d", "display_errors=Off", "-d", "log_errors=On", "-d", "error_log=/dev/stderr", "-d", "error_reporting=E_ALL", "-S", "0.0.0.0:8000", "-t", "public"]
