FROM php:8.3-cli
WORKDIR /app
RUN apt-get update && apt-get install -y libzip-dev unzip && docker-php-ext-install pdo pdo_mysql zip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
EXPOSE 8000
CMD ["php", "-d", "display_errors=Off", "-d", "log_errors=On", "-d", "error_log=/dev/stderr", "-d", "error_reporting=E_ALL", "-S", "0.0.0.0:8000", "-t", "public"]
